# Stripe Configuration
# Get these from https://dashboard.stripe.com/apikeys
# For testing, use keys from a test Stripe account
STRIPE_SECRET_KEY=sk_test_51T4vaiIcMGpBkhgmlyX1RApYVuU7YWEENGznY0qWmtcWIRKMKzXRmsgh5F8UsKHs3l5fsDWTdQqYUzir34ZR9FPc00tg6WTIiI
STRIPE_PUBLIC_KEY=pk_test_51T4vaiIcMGpBkhgmCveUS7XVa4pgapBodqtsOoTgimdB8W1MUJ5ZUuBNdxb0erZUwCHWZdV5DrUwGizuplHBPxXn00871fe5pl
STRIPE_WEBHOOK_SECRET=whsec_d9bb5267a3d9f4249521fed19d13c9025e1ccc7205b4e9be8e451e0a3f0e23d5

# Groq Configuration
# Get this from https://console.groq.com/
GROQ_API_KEY=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
GROQ_MODEL=llama-3.3-70b-versatile
